---
name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/andyattebery/samba-docker:latest
